### ISSUE TITLE
Upvote mutation should use <Form>

### ISSUE THREAD

**Issue by jacob-ebey** [clintonwoo/hackernews-remix-react#3]
Utilizing `<Form>` over an anchor here will allow you to avoid a full page refresh and is semantically more proper.

**Comment by clintonwoo** [comment]
Form might be syntactically more appropriate but the official HN uses an `<a>` tag so I changed it to a `<Link>` instead. Saves worrying about CSS inaccuracies etc.

Thanks!

**Comment by kiliman** [comment]
Hmm... why make a Remix clone if you're not going to use Remix properly? Especially since you put a lot of effort in the README to discuss the architecture.

Using a `<Link>` for mutation is bad, and Hacker News is wrong for doing it as well. If a web crawler visited the page, every article would get upvoted.

**Comment by clintonwoo** [comment]
This site has robots.txt which is disallowing web crawlers.
A link can't be upvoted without being logged in either (returns a redirect to login, web crawlers can't index it if it's redirecting).
An `<a>` tag can set `rel="nofollow"` to indicate to crawlers not to follow the link (which may or may not be respected), I didn't do this since the HTML and CSS is just copied from Hacker News.

As you have pointed out, this project is a clone of Hacker News because it uses the same HTML and CSS.
