### ISSUE TITLE
Use `<Link/>` to take advantage of Remix navigation

### ISSUE THREAD

**Issue by kiliman** [clintonwoo/hackernews-remix-react#4]
Looks like all your links (see item-title.tsx) are using the standard `<a/>` tag, instead of `<Link/>`. This is causing the browser to reload the entire page on every navigation. By using the `<Link/>` component, Remix will issue a client-side fetch, then render the item page.

**Comment by clintonwoo** [comment]
Thanks for pointing this out, the URL only really needed to be an `a` tag when it was external.

The `from` page was missing from the project so I've added that and made it a `Link`.

The upvote is now a Link too.

The external urls weren't actually correctly working on the news feed either so that's fixed. And the domain link is now added too.
